server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false

  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      bandcamp: false
      soundcloud: false
      twitch: false
      vimeo: false
      http: true
      local: false
    filters: []
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: false
    gc-warnings: true

plugins:
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
    sources:
      spotify: false
      applemusic: false
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: true
      vkmusic: false
      tidal: false
      qobuz: false
      ytdlp: false
      jiosaavn: false
    lyrics-sources:
      spotify: false
      deezer: false
      youtube: false
      yandexmusic: false
      vkmusic: false
      lrcLib: false
    youtube:
      countryCode: "KR"
    youtubemusic:
      countryCode: "KR"
      language: "ko"
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - "MUSIC"
      - "ANDROID_VR"
      - "WEB"
      - "TVHTML5"

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs
  level:
    root: info
    lavalink: info
